const TOTAL_TASK_COLOR = "#3754DB";
const IN_PROGRESS_COLOR = "#F2C94C";
const COMPLETED_COLOR = "#00C271";
const OVERDUE_COLOR = "#B80020";
const BACKDROP_WHITE_BG = "#FFFFFF";
const LOADER_COLOR = "#16171D";

export {
  TOTAL_TASK_COLOR,
  IN_PROGRESS_COLOR,
  COMPLETED_COLOR,
  OVERDUE_COLOR,
  BACKDROP_WHITE_BG,
  LOADER_COLOR,
};
